oasisprotocol/playground

oasisriddle/docs/riddle.md, oasisriddle/docs/uganka.md
Adds introductory docs for oasisriddle. Kudos to @matejanez for English translation.
=> oasisriddle: Fine tuning for Consensus 2023

oasisriddle/scripts/deploy.ts
This fixes occasions when the contract code + contract initialization is to big (block gas limit reached) to fit into a single transaction.
=> oasisriddle: Lazy deploy coupon codes

oasisswag/test/RandomSwag.ts
Followup to #7 . Fixes tests for NFT.
=> oasisswag: Fix tests for NFT mint

opl-secret-ballot/frontend/package.json, opl-secret-ballot/frontend/src/contracts.ts, opl-secret-ballot/pnpm-lock.yaml
Followup to https://github.com/oasisprotocol/playground/pull/5: The backend package name changed `@oasislabs` -> `@oasisprotocol`.
=> deps(opl-secret-ballot): Fix backend package name

CONTRIBUTING.md, README.md
Followup to #27 containing fixes proposed by @aefhm.
=> CONTRIBUTING, README: Fix some typos

package.json, src/components/ProjectDialog.tsx, src/components/ProjectListItem.tsx, src/index.css, yarn.lock
Add react-markdown library to the project in order to be able to style project description in the description.yaml files.
Screenshots:
Before:
After:
=> Project description markdown functionality

src/App.tsx
Implement a button 'Add your dApp' linking to 'Contributing to the Oasis Playground' on GitHub.
**Before:**
**After:**
=> Add contribution button

src/components/ProjectDialog.tsx
Needs to be tested if it's secure.
=> Open markdown links in new tab

src/components/ProjectDialog.tsx
Adjust code to be able to display multiple authors and tutorials.
=> Display multiple authors and tutorials

package.json, yarn.lock
Fixes [https://github.com/oasisprotocol/playground/security/dependabot/1](https://github.com/oasisprotocol/playground/security/dependabot/1)
Fixes [https://github.com/oasisprotocol/playground/security/dependabot/2](https://github.com/oasisprotocol/playground/security/dependabot/2)
=> Update vite dependency

src/projectData.ts
=> Add support for jpg screenshots

package.json, src/components/ProjectList.tsx, src/components/ProjectListItem.tsx, src/main.tsx, src/projectData.ts, src/types.ts, yarn.lock
Enhancement suggested at [https://github.com/oasisprotocol/playground/issues/40](https://github.com/oasisprotocol/playground/issues/40)
**Before:**
**After:**
=> Add unique anchors for projects

src/components/ProjectList.tsx
fixed: https://github.com/oasisprotocol/playground/pull/68#discussion_r1725313783
=> Rename handleSingleTagClick to handleTagClick

src/components/ProjectDialog.tsx, src/components/ProjectItemLanguages.tsx, src/components/ProjectItemTags.tsx, src/components/ProjectList.tsx, src/components/ProjectListItem.tsx
Changes implemented based on the feedback provided in this comment - https://github.com/oasisprotocol/playground/pull/70#pullrequestreview-2263306587
=> Add language and paratime filtering inside of projects

src/components/ProjectList.tsx, src/components/SearchFilter.tsx
Implemented enhancement: [https://github.com/oasisprotocol/playground/issues/78]
=> Include paratimes, tags and languages to search

src/components/ProjectList.tsx
Fixed Issue: [#81](https://github.com/oasisprotocol/playground/issues/81)
=> Make folder name searchable

src/components/ProjectList.tsx
Fixes: [#85 ](https://github.com/oasisprotocol/playground/issues/85)
=> Add filters to URL queries

biome.json, public/projects.json, src/components/Filters.tsx, src/components/ProjectDialog.tsx, src/generate-projects-json.mjs, src/types.ts
"", null, and missing field => null
=> Normalize missing licenses and demoUrls

scripts/projects/README.md, scripts/projects/TaikaiImporter.ts, scripts/projects/projects.ts
Fixes #127 
This PR adds:
- TaikaiImporter.ts for scraping Oasis hackathon projects from taikai.network.
=> Add taikai importer

.github/workflows/ci-links.yml, .gitignore, README.md, linkinator.config.json, package.json, scripts/run-linkinator.sh, yarn.lock
Related to https://github.com/oasisprotocol/playground/pull/137#pullrequestreview-3066748111
Not ready to be enforced as CI - there are broken links even after https://github.com/oasisprotocol/playground/pull/137
```diff
projects/zk-pal/description.yaml.linkinator.md
-  [500] https://taikai.network/regisgraptin
[200] https://taikai.network/spoyte117
[200] https://taikai.network/cryptocanal/hackathons/ethdam2025/projects/cmai9r0db00xii8o9daaz8rbn
[200] https://github.com/oasisprotocol/demo-rofl-chatbot
[200] https://www.youtube.com/watch?v=W9V_S_5Lqsk
projects/zeo-kuessr/description.yaml.linkinator.md
[200] https://github.com/techiepriyansh
[200] https://github.com/MayankMittal1
[200] https://github.com/levihackerman-102
[200] https://ethglobal.com/showcase/zeokuessr-69vv0
[200] …
```
=> Add linkinator to find broken links in projects
